version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: file-storage-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: file_storage
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
